#!/bin/bash

xraytype="$1"
case "$xraytype" in
    "vless-tcp")
        ;;
    "vless-xhttp")
        ;;
    *)
        echo "Usage: ./xray-install (vless-tcp, vless-xhttp)" 
        exit 1
        ;;
esac

echo "Будет установлен Vless с транспортом $xraytype"
sleep 3

# Включаем bbr
bbr=$(sysctl net.ipv4.tcp_congestion_control)
if [ "$bbr" = "net.ipv4.tcp_congestion_control = bbr" ]; then
echo "bbr уже включен"
else
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
echo "bbr включен"
fi

# Устанавливаем нужный qdisc
qdisc=$(sysctl net.core.default_qdisc)
if [ "$qdisc" = "net.core.default_qdisc = fq" ]; then
echo "qdisc=fq уже установлен"
else
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
sysctl -p
echo "qdisc=fq установлен"
fi

# Устанавливаем необходимые пакеты
apt install qrencode curl jq -y

# Устанавливаем ядро Xray, если оно не установлено
systemctl stop xray
if [ $? -ne 0 ]; then
    apt update
    bash -c "$(curl -4 -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
fi

# Генерируем ключи для сервера, если их нет
privatekey=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/PrivateKey/ {print $2}')
if [ -z "$privatekey" ]; then
    echo "Генерируем ключи для сервера"
    xray x25519 > /usr/local/etc/xray/.keys
    privatekey=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/PrivateKey/ {print $2}')
    if [ -z "$privatekey" ]; then
        echo "ОШИБКА: приватный ключ не был сгенерирован"
        exit 2
    fi
fi

# Создаем файл конфигурации Xray, подставляя значения переменных в шаблоны
jq --arg privatekey "$privatekey" \
    '.inbounds[0].streamSettings.realitySettings.privateKey=$privatekey' \
    "./config-${xraytype}.json" > /usr/local/etc/xray/config.json || exit 3

# Устанавливаем скрипт управления пользователями
cp ./xray-user.py /usr/local/bin/xray-user

echo "Xray-core успешно установлен"
echo "Создайте пользователя с помощью \`xray-user -add username\`, перезапустите сервис с \`sudo systemctl restart xray\`"
echo "Для получения ссылки и QR-кода введите \`xray-user -link username\`"


